CREATE TABLE `data_platform_campaign_header_data`
(
  `Campaign`                         int(16) NOT NULL,
  `CampaignType`                     varchar(4) NOT NULL,
  `CampaignOwner`                    int(12) NOT NULL,
  `CampaignOwnerBusinessPartnerRole` varchar(40) NOT NULL,
  `PersonResponsible`                varchar(40) NOT NULL,
  `ValidityStartDate`                date NOT NULL,
  `ValidityStartTime`                time NOT NULL,
  `ValidityEndDate`                  date NOT NULL,
  `ValidityEndTime`                  time NOT NULL,
  `OperationStartDate`               date NOT NULL,
  `OperationStartTime`               time NOT NULL,
  `OperationEndDate`                 date NOT NULL,
  `OperationEndTime`                 time NOT NULL,
  `Description`                      varchar(60) NOT NULL,
  `Introduction`                     varchar(200) DEFAULT NULL,
  `LongText`                         varchar(1000) NOT NULL,
  `Site`                             int(16) NOT NULL,
  `Project`                          int(16) DEFAULT NULL,
  `WBSElement`                       int(8) DEFAULT NULL,
  `Tag1`                             varchar(40) DEFAULT NULL,
  `Tag2`                             varchar(40) DEFAULT NULL,
  `Tag3`                             varchar(40) DEFAULT NULL,
  `Tag4`                             varchar(40) DEFAULT NULL,
  `DistributionProfile`              varchar(4) NOT NULL,
  `PointConditionType`               varchar(4) NOT NULL,
  `QuestionnaireType`                varchar(4) DEFAULT NULL,
  `QuestionnaireTemplate`            varchar(4) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `CreateUser`                       int(12) NOT NULL,
  `LastChangeUser`                   int(12) NOT NULL,
  `IsReleased`                       tinyint(1) DEFAULT NULL,
  `IsCancelled`                      tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Campaign`),

    CONSTRAINT `DPFMCampaignHeaderDataCampaignType_fk` FOREIGN KEY (`CampaignType`) REFERENCES `data_platform_campaign_type_campaign_type_data` (`CampaignType`),
    CONSTRAINT `DPFMCampaignHeaderDataCampaignOwner_fk` FOREIGN KEY (`CampaignOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMCampaignHeaderDataCampaignOwnerBPRole_fk` FOREIGN KEY (`CampaignOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMCampaignHeaderDataSite_fk` FOREIGN KEY (`Site`) REFERENCES `data_platform_site_header_data` (`Site`),
    CONSTRAINT `DPFMCampaignHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMCampaignHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMCampaignHeaderDataDistributionProfile_fk` FOREIGN KEY (`DistributionProfile`) REFERENCES `data_platform_distribution_profile_distribution_profile_data` (`DistributionProfile`),
    CONSTRAINT `DPFMCampaignHeaderDataPointConditionType_fk` FOREIGN KEY (`PointConditionType`) REFERENCES `data_platform_point_condition_type_point_condition_type_data` (`PointConditionType`),
    CONSTRAINT `DPFMCampaignHeaderDataQuestionnaireType_fk` FOREIGN KEY (`QuestionnaireType`) REFERENCES `data_platform_questionnaire_type_questionnaire_type_data` (`QuestionnaireType`),
    CONSTRAINT `DPFMCampaignHeaderDataQuestionnaireTemplate_fk` FOREIGN KEY (`QuestionnaireTemplate`) REFERENCES `data_platform_questionnaire_tmpl_questionnaire_tmpl_data` (`QuestionnaireTemplate`),
    CONSTRAINT `DPFMCampaignHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMCampaignHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
